# 项目相关配置
lemon:
  # 名称
  name: Lemon-Ruoyi
  # 版本
  version: ${lemon-ruoyi.version}
  # 版权年份
  copyrightYear: 2023
  # 缓存懒加载
  cacheLazy: false

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /

# Spring配置
spring:
  profiles:
    active: @profiles.active@
